apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80

    - name: busybox-container
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - while true; do
            wget -qO- http://127.0.0.1;
            sleep 5;
          done;
